app/controllers/problems_controller.rb, app/views/problem_sets/show.html.erb, app/views/problems/_admin.html.erb, config/routes.rb
Added list of problem sets under each problem and list of groups under each problem set.
Please apply these changes to the train site :)
=> Problem set lists

.travis.yml, script/install/postgresql.bash
Started failing in https://github.com/NZOI/nztrain/pull/39.
See https://docs.travis-ci.com/user/database-setup/#postgresql.
=> Fix PostgreSQL error on Travis CI

app/assets/stylesheets/style.css
Choosing a minimal change for deployment to check if the server restarts correctly. If it succeeds, we can make the other controller and UI changes.
=> inline-block elements not showing background colour

app/assets/stylesheets/scaffold.css, app/models/language.rb, app/views/problems/submit.html.erb, db/languages.yml, script/install/debootstrap.bash
Improve readability and add details about the compilers used. Note that this change assumes PR #45 is merged.
=> Update submit page

app/assets/stylesheets/scaffold.css, app/models/language.rb, app/views/problems/submit.html.erb, db/languages.yml, script/install/debootstrap.bash
=> Show compiler version info

app/models/language.rb, app/views/problems/submit.html.erb, app/views/submissions/_form.html.erb
Currently the default option is the first in the dropdown, which is C11.
=> Sort language dropdown and set default to C++17

db/languages.yml
=> Make J's version number consistent

app/models/submission/judge_data.rb
Was originally "Runtime Error"
=> Display "Complier Error" on compilation failure

script/install/whenever.bash
Make the command actually do what it says it does.
=> bundle list [args] is deprecated

app/assets/stylesheets/submission.css, app/views/submissions/show.html.erb
=> Show failing sample case details by default

app/assets/javascripts/application.js, app/assets/stylesheets/nav-superfish.css.erb, app/assets/stylesheets/style.css, app/views/layouts/scaffold.html.erb
=> Fix scroll draw on Safari (deploy)

app/views/problems/submit.html.erb, spec/features/submissions_spec.rb
=> Fix ambiguous matches in submission spec

app/views/contests/scoreboard.html.erb
Based on commit 4fc3166 by Holmes98 on branch 'scoreboard-update'.
=> Fix current user detection on scoreboard

app/views/submissions/show.html.erb
Open for discussion, but I always disliked the submission messages. Particularly "There's room for improvement". Would be nice to use things which are more encouraging.
=> Nice messages

app/assets/stylesheets/submission.css, app/views/submissions/show.html.erb
=> Fix inspection formatting with float right

app/controllers/contests_controller.rb, app/controllers/schools_controller.rb, app/controllers/user_controller.rb, app/policies/contest_relation_policy.rb, app/views/contests/contestants.html.erb, app/views/schools/_form.html.erb, app/views/schools/edit.html.erb, app/views/schools/index.html.erb, app/views/schools/show.html.erb, app/views/user/_form.html.erb, config/routes.rb
Currently any user can add a school to the school list, so this is required to allow for moderation. I did some cleanup last year through `rails console` but that isn't really ideal.
In the future, we might want to consider restricting additions to the list.
=> Add interfaces for managing schools

app/assets/stylesheets/scaffold.css, app/models/user.rb, app/views/accounts/registrations/new.html.erb, app/views/accounts/settings/edit.html.erb
* Expand detail on graduation date and eligibility
* Reformat to use headers instead of paragraphs
* <strike>Make "new school" slightly more noticeable</strike>
* Improve spacing of header for small devices
Avoided changing any stylesheets for fear of impacting other pages
<strike>Merge after PR #125 </strike>
=> Update registration page

app/assets/stylesheets/main_table.css, app/controllers/contests_controller.rb, app/models/contest.rb, app/models/contest_relation.rb, app/views/contests/_form.html.erb, app/views/contests/edit.html.erb, app/views/contests/info.html.erb, app/views/contests/scoreboard.html.erb, app/views/contests/show.html.erb, app/views/layouts/application.html.erb, db/migrate/20200418113600_add_live_scoreboard_field.rb, db/migrate/20200418113601_add_offical_contestants.rb, db/schema.rb
PRs #135 and #123 have already been deployed on the server and are now both approved. Let's merge them into "master" by fast-forwarding (to avoid diverging from the "deployed" branch).
=> Fast-forward "master" to "deployed" (#135, #123)

spec/controllers/application_controller_spec.rb
Merge after #171 (since these specs also test the code in #171).
=> Add specs to check that XML is forbidden for non-admins

app/services/isolate.rb, app/workers/judge_submission_worker.rb, script/install/config.bash, script/install/isolate.bash, script/install/isolock.bash
Also see https://github.com/NZOI/isolock/commit/94b13d35eecca18665d1dbd919ed718dfb078e1d for required changes to isolock.
=> Update to latest version of isolate

Gemfile.lock
We forgot to update Gemfile.lock in #162.
=> Remove activerecord-session_store from Gemfile.lock

config/environment.rb
Remove unused stuff to make it easier to update.
Merge using "Rebase".
=> Clean up environment.rb

config/application.rb
These lines have been commented a while or wouldn't provide a change
from the rails default if uncommented.
=> Remove some commented lines from config/application.rb

app/models/enumeration.rb
https://bugs.ruby-lang.org/issues/12005
=> Fix Ruby 2.4 deprecation: Fixnum => Integer

.github/workflows/ci.yml
Depends on #225 (and additional fixes).
Closes #245.
=> Add CI check that db/schema.rb matches result of migrations

.standard_todo.yml, app/controllers/accounts/registrations_controller.rb, app/controllers/groups/members_controller.rb, app/controllers/importers/problem_series_controller.rb, app/controllers/problems_controller.rb, app/scrubbers/loofah/scrubbers/math_jax.rb, app/workers/problem_series/import_worker.rb, db/migrate/20131209063832_fix_bad_markdown.rb, lib/file_size_validator.rb
Stacked on #286 (not sure if I'm doing it right, can't remember if/how I can stack PRs without using Graphite's UI).
~~(The first commit in this PR is not directly related to standardrb, but it arose out of the last commit on #286.)~~ *Changed and moved to #289 (see https://github.com/NZOI/nztrain/pull/287#pullrequestreview-2780141176)*
=> Some manual style fixes for standardrb

spec/features/problem_browsing_spec.rb
This page relies on a lot of ApplicationPresenter / StrongPresenter
features which I am trying to write out, so seemed worthwhile having a
small test for faster iterate.
=> Add basic feature test for problem browsing

script/install/redis-installer.bash
=> Clean up Redis install script

Gemfile, Gemfile.lock, app/assets/javascripts/test_sets.js.coffee
We are not using CoffeeScript so we don't need it.
=> Remove coffee-rails gem

.standard_todo.yml, spec/controllers/accounts/passwords_controller_spec.rb, spec/spec_helper.rb
Just some small random things I came across.
=> Some standardrb fixes

app/controllers/contests_controller.rb, app/models/contest.rb
=> Reduce DB queries for schools when using scoreboard

app/assets/javascripts/application.js
Alternative fix to #305/#306 that avoids adding a scrollbar and preserves the linear transition.
=> Fix clipping in expanded problem set item lists

.gitignore
=> Ignore .DS_Store files from macOS
