app/controllers/submissions_controller.rb
Currently, we updating (editing) a submission if you change the language then the submission will appear to retain the original language.
=> Correctly record the new language selected for the updated submission

script/install/debootstrap.bash
Python 2 used to be installed automatically as a dependency of python-software-properties, but that was removed in commit 1ebd684 ("Remove debootstrap package for Ubuntu 12.04", 2020-01-21).
Python 2 has reached end-of-life and is no longer displayed as an option for submissions, so it shouldn't be installed by default. However, some deployments might need to support old Python 2
submissions, so I've added the commands as comments.
=> Add commented-out commands to install Python 2 in the chroot

script/install/debootstrap.bash
(in debootstrap script)
The "universe" component is enabled for the "$SUITE" repository, so it should also be enabled for "$SUITE-security" to get security updates.
Discovered because it caused dependency errors when building V8 (https://github.com/NZOI/nztrain/pull/49#discussion_r369930432).
The sources.list file could do with some more cleanup. Leaving it for now to reduce merge conflicts with commit 9f5ff36 ("Fix isolate root path in debootstrap script", 2019-01-30).
This will need to be applied manually on the server.
=> Enable "universe" component of security repository in sources.list

app/services/isolate.rb, db/languages.yml, script/install/debootstrap.bash
This PPA is recommended by https://www.haskell.org/downloads/linux/.
An earlier attempt was made in #27.
(We should probably refactor the debootstrap script at some point to add all the PPAs at the start so it doesn't need to run `apt-get update` multiple times.)
=> Update Haskell (using hvr's PPA)

app/models/language.rb, app/views/problems/submit.html.erb
See https://github.com/NZOI/nztrain/pull/64#discussion_r372315509.
If the last submitted language is no longer selectable, or the user has not yet made any submissions, it will default to the first option in the dropdown. Also, since the ordering of the current languages
is manually defined, I've removed `Language.default`.
=> Set each user's default option to their last submitted lanugage

app/views/problems/submit.html.erb
The safe navigation operator "&." requires Ruby >= 2.3. See https://github.com/NZOI/nztrain/pull/67#issuecomment-580018076.
.try() is provided by ActiveSupport.
=> Use .try() instead of &. to get the last submission's language id

db/migrate/20110819224757_devise_create_users.rb, db/migrate/20110820005833_create_test_cases.rb, db/migrate/20110820010205_create_problems.rb, db/migrate/20110820013719_create_submissions.rb, db/migrate/20110904033519_create_contest_relations.rb, db/migrate/20110904033742_create_contests.rb, db/migrate/20110924030742_create_groups.rb, db/migrate/20120119025544_create_problem_sets.rb, db/migrate/20120128235138_create_evaluators.rb, db/migrate/20120201113029_add_sessions_table.rb, db/migrate/20120210235859_create_test_sets.rb, db/migrate/20130107015143_create_ai_contests.rb, db/migrate/20130107025725_create_ai_submissions.rb, db/migrate/20130108005444_create_ai_contest_games.rb, db/migrate/20130926105411_create_requests.rb, db/migrate/20131001083843_create_file_attachments.rb, db/migrate/20131007002316_create_test_case_relations.rb, db/migrate/20131013045616_create_languages.rb, db/migrate/20131208014408_add_language_group_model.rb, db/migrate/20131221014009_create_user_problem_relation.rb, db/migrate/20150330223537_create_forem_topics.forem.rb, db/migrate/20150330223538_create_forem_posts.forem.rb, db/migrate/20150330223546_create_forem_categories.forem.rb, db/migrate/20160123214252_create_contest_supervisors.rb, db/schema.rb
See commit messages for details.
This pull request changes the timestamp columns in the version-controlled schema and the migrations to match the current schema on the server. If we want to make all the timestamp columns consistently use `null: true` or `null: false` it should be done separately.
Note that there is another inconsistency which is not addressed here: the `limit: 128` attribute on the users.encrypted_passwords column (also introduced in [fe025a8](https://github.com/NZOI/nztrain/commit/fe025a81727e2e467b6f9f7ed7be4f8222c50709#diff-1acd2e7e27a227829d5d14a91c863bb6L517)).
=> Fix null attributes of timestamps to match server

app/models/language.rb, db/languages.yml, script/install/debootstrap.bash, script/install/v8.bash
Compared Nodejs and V8 engine. Nodejs displayed much slower I/O than Python and the syntax for receiving input is horrible. V8 provides `readline` and much more competitive performance. Hence, we propose to support JavaScript by compiling the V8 engine from source and installing it in the sandbox. Has been tested on a local install of nztrain.
JavaScript is a popular language likely to remain relevant for the foreseeable future. It is commonly taught in schools to a basic level. I have received a few requests for us to support it.
**Note: The updated install script has not been tested.**
This has already been done on codeforces. https://codeforces.com/blog/entry/10024
https://v8.dev/docs/build
https://remusao.github.io/posts/compiling-v8-ubuntu-16-04.html
=> Add JavaScript

app/workers/problem_series/import_worker.rb
From #106.
The problem series import worker previously set the visibility of the file attachment containing the imported statement to 'protected'.
That doesn't make sense, because 'protected' means users can view the file if they are *not* currently competing (comment: [app/models/filelink.rb:17](https://github.com/NZOI/nztrain/blob/843d01e5a25965046fc06742beb615878065d11e/app/models/filelink.rb#L17), logic: [app/policies/filelink_policy.rb:26](https://github.com/NZOI/nztrain/blob/843d01e5a25965046fc06742beb615878065d11e/app/policies/filelink_policy.rb#L26)).
As discussed in #106 (specifically https://github.com/NZOI/nztrain/issues/106#issuecomment-617556022 by @Holmes98), the purpose of 'protected' is probably to prevent access to file attachments of other problems/groups during …
=> Change visibility of problem statement attachment to 'public' in importer

app/views/contests/_index.html.erb
- Only display it to admins
- Change the heading from "User" to "Owner"
- Display the username (and link to their profile) instead of ID
Based on commits af301f9 (from #103) and 784e99c (from branch 'scoreboard-update').
I used `handle(contest.owner)` instead of `contest.owner.username` so it doesn't crash if the user has been deleted. A side effect is that it displays the full name of the user in addition to their username.
If the owner has been deleted it displays "DELETED". The link will point to a somewhat arbitrary page (e.g. on /contests it points to /contests/my, and on /contests/current it points to /contests/active; I'm not sure exactly why). This doesn't seem like a major issue, and it is already widespread (all the places that use `link_to handle(XXX), XXX` where `XXX` may be …
=> Update owner column in the contest index pages

app/views/layouts/contest.html.erb
- Only display it to admins
- Display the username (and link to their profile) instead of ID
For consistency with #109.
=> Update owner in contest page

app/views/contests/_index.html.erb, app/views/layouts/contest.html.erb
Taken from PR #103, commit af301f9. See previous review comments about pluralisation on https://github.com/NZOI/nztrain/pull/103#discussion_r411322977.
=> Add unit 'hours' to the contest duration in the interface

config/routes.rb
In theory it might make sense to filter by multiple users/problems, but currently the code assumes each parameter contains a single ID.
=> Forbid commas in :by_user and :by_problem segments of /submissions route

app/controllers/submissions_controller.rb, app/views/submissions/_page.html.erb, app/views/submissions/index.html.erb
params[:by_user] is usually a string, which will never compare equal to current_user.id (an integer).
The main effect is that non-staff users weren't authorized to view /submissions/by_user/:user_id/by_problem/:problem_id even when :user_id was their own ID. Also, some of the UI messages were wrong (e.g. "No submissions found" instead of "You have no submissions").
Use params[:by_user].to_i when comparing to current_user.id.
(Note: `params[:by_user] == current_user.id.to_s` almost works but can produce incorrect results if params[:by_user] has leading zeros.)
Also, store a string in params[:by_user] when the route is /submissions/my for consistency.
=> Fix type mismatch when checking :by_user URL parameter

app/assets/javascripts/application.js, app/models/user.rb, app/views/accounts/registrations/new.html.erb, app/views/accounts/settings/edit.html.erb
Add javascript that 'disables' graduation date and school fields for non-NZers.
Graduation date checks not reinforced server side but no major issues are forseen.
Requires PR #128 <strike>which requires PR #125</strike>
=> Hide fields on reg and profile pages for non-NZers

app/helpers/application_helper.rb
The first patch is a code change that was made directly on the production server, I'm not sure who originally wrote it or under what conditions the weighting is 0.
=> Fix divide-by-zero in ApplicationHelper.progress_bar when weighting is 0

script/install.bash
Fixes [Travis CI build failure](https://travis-ci.org/github/NZOI/nztrain/builds/679338637) when removing maxmind.bash in #108.
=> Run 'apt-get update' before installing any packages to avoid stale package index

app/controllers/groups_controller.rb, app/views/groups/scoreboard.html.erb, app/views/layouts/group.html.erb
It was discussed at the AGM that it would be motivating for the training squad to see the progress of their pairs. Admins have access to a scoreboard which offers exactly this. This pull request seeks to give group members permission to see the group scoreboard.
* These changes are untested (I don't have a VM setup to do that).
* This means all members of a group can see the progress of all other members in that group. This would apply to all groups.
Would be grateful if someone could please review this.
=> Give group members access to scoreboard

spec/factories/ai_contest_games.rb, spec/factories/ai_contests.rb, spec/factories/ai_submissions.rb, spec/factories/contest_relations.rb, spec/factories/contest_scores.rb, spec/factories/contest_supervisors.rb, spec/factories/contests.rb, spec/factories/evaluators.rb, spec/factories/groups.rb, spec/factories/languages.rb, spec/factories/problem_sets.rb, spec/factories/problems.rb, spec/factories/settings.rb, spec/factories/submissions.rb, spec/factories/test_cases.rb, spec/factories/test_sets.rb, spec/factories/users.rb
See https://thoughtbot.com/blog/deprecating-static-attributes-in-factory_bot-4-11.
Warning message:
```
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:
ai_contest_id { 1 }
To automatically update from static attributes to dynamic ones,
install rubocop-rspec and run:
rubocop \
--require rubocop-rspec \
--only FactoryBot/AttributeDefinedStatically \
--auto-correct
```
Fixed using the suggested command (needed to temporarily switch to Ruby 2.6 to install the rubocop-rspec gem).
Merge after #148.
=> Fix FactoryBot deprecation warning: "Static attributes will be removed"

Gemfile, Gemfile.lock
This newer version workers with older system libraries (as far as I can tell) and workers with new ruby / rails versions so is a requirement for eventually upgrading Rails
=> Upgrade rmagick

app/assets/stylesheets/code.css
The recent upgrade to pygments.rb 1.1.2 (#164) caused a small issue with the line numbers on syntax-highlighted code blocks (including test case inputs and outputs). It caused the numbers "1" and "2" to both appear next to the first line on top of each other:
This happened because of a change in Pygments that intentionally inserted an empty <span> element at the beginning to preserve leading empty lines.[\[1\]][1][\[2\]][2] (See https://github.com/NZOI/nztrain/pull/164#issuecomment-1427154232 an example of the HTML.)
The line numbers are added by our CSS, and the old selector treated this dummy span as a line.
The spans that correspond to actual lines have an ID attribute of the form "line-1", "line-2" etc. So this commit fixes the issue by changing the selector to only match spans with …
=> Fix line number issue when displaying submission source etc.

app/controllers/user_controller.rb, app/helpers/user_helper.rb, app/presenters/user_presenter.rb, app/views/user/show.html.erb, spec/presenters/user_presenter_spec.rb
This is a pretty thin wrapper around the User, providing only some helpers for permissions. We *probably* have to write out the strong presenters library due to rails upgrade / ruby upgrade reasons, so this is a good place to start.
=> Refactor to remove the UserPresenter service object

app/controllers/application_controller.rb
Commit message:
> The `content_type=` check implemented in #169 runs fairly early (which is good) but it is slightly fragile (e.g. it is bypassed if `response.content_type=` is called directly).
> 
> Add an `after_filter` that raises an error if XML slipped through.
I'm not sure what's the idiomatic behaviour for such assertion failures, so I just used `raise "..."` (which [raises a RuntimeError](https://ruby-doc.org/3.2.1/Kernel.html#method-i-raise)).
=> Add an `after_filter` to assert that XML is forbidden

script/install/rvm.bash
> The official installation method[1] uses
> 
>     gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys ...
> 
> However, the keyserver pool.sks-keyservers.net has been discontinued.[2]
> 
> Of the popular alternatives,
> 
>  - keys.gnupg.net is gone (it was an alias to pool.sks-keyservers.net)
>  - keys.openpgp.org doesn't have the keys of the RVM maintainers
>  - pgp.mit.edu was unreliable for me (really slow, only returns the keys some of the time)
>  - keyserver.pgp.com timed out for me
>  - keyserver.ubuntu.com works
> 
> So switch to keyserver.ubuntu.com.
> 
> (An alternative approach is to download the public keys from https://rvm.io/mpapis.asc and https://rvm.io/pkuczynski.asc as described in [3]. This method is considered less secure because it does …
=> Fix rvm install script by changing the OpenPGP keyserver to keyserver.ubuntu.com

script/install/redis.bash
> Redis 7.0 (the current stable) and 6.2.7+ break qless, see https://www.github.com/seomoz/qless-core/issues/89.
> 
> Lock the version to 6.2.6 until that issue is fixed.
>
> ...
---
I submitted a PR to qless that fixes the bug ([seomoz/qless-core#90](https://www.github.com/seomoz/qless-core/pull/90)) in July 2022 ~~but there has been no response~~. I pinged them again just now in the main repo ([seomoz/qless#297](https://www.github.com/seomoz/qless/issues/297)), I hope ~~they'll finally apply the patch so~~ we don't end up stuck on an unsupported Redis version. (Worst case we can fork qless.)
EDIT: I've just realised they did try to merge my patch but had to revert it due to build errors: https://github.com/seomoz/qless-core/commit/49f707402b7f53006d0696cb49ae5baa …
=> Temporarily lock the Redis version to 6.2.6 to fix qless error

script/install/rbenv.bash
They renamed the branch from "master" to "main".[1] Their README suggests to use "HEAD" instead of hard-coding the branch name.[2]
[1]: https://github.com/rbenv/rbenv-installer/commit/e017714f3e4eba6b18c3e5c041d169df832fbb2f
[2]: https://github.com/rbenv/rbenv-installer/commit/b4e8f205dc6d47885e574dba23dba855a9f3b512
=> Fix URL of rbenv-installer script

script/install/bundler.bash
> The recently-released Bundler 2.4 requires Ruby >= 2.6, but we use Ruby 2.3.8 so `gem install bundler` fails with
> 
> ```
> ERROR:  Error installing bundler:
>         bundler requires Ruby version >= 2.6.0.
> ```
> 
> Note that this is relevant when using rbenv, but not when using rvm because it includes Bundler by default:
> https://github.com/rvm/rvm/blame/9d55c729d536dab23982946a5b65d10d0301ff78/docs/upgrade-notes.md#L29
*EDIT: Originally this PR just required Bundler < 2.4, but later we changed it to require < 2.0. See commit c2462884c9c98e98fd355f69eb8ac994e537a886 for details.*
There is a subtle footgun with the version variable that I introduced: if it contains spaces (e.g. `"< 2.4"`) then the version constraint will be split into multiple command line …
=> Install Bundler 1.x instead of latest version (2.4)

db/migrate/20120805061859_system_mailer_settings.rb
This is softly deprecated in Rails 4.0 [1] and are fully removed under Rails 4.1, so they need to be replaced before we can upgrade.
[1] https://guides.rubyonrails.org/4_0_release_notes.html#active-record-deprecations
=> Refactor calls to method_missing find_or_create_by_*

app/models/user.rb
Returning from a block isn't really supported - instead you're supposed to use break / next to early return from a block. In any rate, this callback just needs to return true, which we can do via implicit return.
Rails 4.1 treats a non-local jump in a ActiveRecord::Callback as an error, so we have to fix this before.
=> Avoid a local jump error caused by trying to return from a block

config/initializers/redis.rb
Makes dockerisation much easier as we can embed a version of this file in the image that is looking for specific env vars. More recent rails versions ditch the .yml.template concept for just providing more easily customisable .yml's by default. This will move us towards doing this, also.
=> Allow redis config to use ERB variables

app/models/contest.rb, app/models/group.rb, app/models/problem.rb, app/models/problem_set.rb, app/models/role.rb, app/models/submission.rb, app/models/test_case.rb, app/models/user.rb
(Extracted from commit 04b1c7cf56f5d74b8c02a164f5cfac4ca79223fe of #188)
The "distinct" method is available since Rails 4.0.0 [1] (and was available as "uniq" since Rails 3.2.0 [2]), so we no longer need to define our own "distinct" scope.
And as of Rails 4.1 it is forbidden to define a scope with a conflicting name[3], so we have to remove our "distinct" scope.
[1] https://github.com/rails/rails/commit/a1bb6c8b06db83546179175b9b2dde7912c86f9b
[2] https://github.com/rails/rails/commit/562583c7667f508493ab8c5b1a4215087fafd22d
[3] https://www.github.com/rails/rails/pull/13450
=> Remove custom "distinct" scope, since it's provided by Rails, and Rails 4.1 forbids that name

Gemfile, Gemfile.lock
Rails' activesupport 4.1.* depends on json ~> 1.7 (i.e < 2.0) [1], so in order to upgrade to Rails 4.1 we need to downgrade json from 2.6.3 to 1.8.6 (the highest < 2.0).
But json < 2.3 has a security vulnerability, CVE-2020-10663 [2]. So we also add a dependency on the gem 'json_cve_2020_10663', which monkey-patches the json gem to protect from this vulnerability.
(Verified that the CVE is patched using the code listed on [3].)
[1] https://rubygems.org/gems/activesupport/versions/4.1.16
[2] https://www.ruby-lang.org/en/news/2020/03/19/json-dos-cve-2020-10663/
[3] https://github.com/rails-lts/json_cve_2020_10663
Suggested-by: Jonathan Khoo <jkhoo98@gmail.com>
=> Downgrade json to 1.8.6 for Rails 4.1 compatibility; add workaround for CVE-2020-10663

script/install/assets.bash, script/install/bundle.bash, script/install/migrate.bash, script/install/pull.bash
Indenting the output of verbose commands such as `rake db:migrate` is nice because it visually separates their output from everything else, but there are a couple of problems with the current approach:
1. It only indents stdout, so messages written to stderr are de-synchronized and can appear out of order, which is confusing. [Can be fixed by also indenting stderr: `... |& sed ...`]
2. Some commands (e.g. `bundle install`) use colour when their output is a terminal. Piping their output suppresses this behaviour, which is a shame. [Can't be fixed easily]
3. The complex filter for `bundle install` is broken:
- It tries to remove lines of the form "Using <gem> (<version>)", but the regex is broken (Bundler's current output format doesn't contain parentheses) so these lines are still …
=> Don't indent output in install scripts

app/controllers/contests_controller.rb, app/models/contest.rb, app/models/contest_relation.rb
It was using an implicit join reference, which was deprecated in Rails 4.0 and removed in Rails 4.1.
Currently throws the following error:
```
PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "users"
LINE 1: ...t_id" = $1  ORDER BY contest_relations.school_id, users.user...
^
: SELECT "contest_relations".* FROM "contest_relations"  WHERE "contest_relations"."contest_id" = $1  ORDER BY contest_relations.school_id, users.username
```
Under Rails 4.0, it was logging this warning:
```
DEPRECATION WARNING: It looks like you are eager loading table(s) (one of: contest_relations, users) that are referenced in a string SQL snippet. For example: 
Post.includes(:comments).where("comments.title = 'foo'")
Currently, Active Record recognizes the table in the string, and knows to JOIN …
```
=> Fix contestants page

Gemfile, Gemfile.lock
Devise 3.4.0 added support for Rails 4.2 so it's in the critical path for that set of upgrades. 3.4.1 fixed an issue with 3.4.0, so seems worth the the patch bump.
https://github.com/heartcombo/devise/blob/3-stable/CHANGELOG.md#341---2014-10-29
=> Upgrade devise to 3.4.1

.gitignore, config/initializers/secret_key_base.rb, config/initializers/secret_token.rb
secret_key_base was added in Rails 4 and replaces secret_token.
~~This PR is intended to merge using the "Rebase" strategy.~~ *Update: I reverted the second commit (see below), so now should use squash & merge and clean up the commit message.*
=> Add config.secret_key_base

app/views/layouts/application.html.erb
It's referencing a GA product that doesn't exist, no-one has access to that property, and it's just cruft.
=> Remove (commented out) google analytics code

config/environments/development.rb, config/initializers/mail_interceptor.rb
This makes rails upgrades easier, as it means the diff between the
template-added is near-zero. There's no reason not to set this up here,
we just have to be a little careful about rails load order (use
Mail#register_interceptor instead of ActionMailer).
=> Extract DevelopmentMailInterceptor setup from config/environments/

app/views/test_cases/index.html.erb, config/environment.rb, lib/ext/string.rb
Rails 3 has a built-in truncate method that we can use instead.
Also remove the constant SHORTEN_LIMIT, it is only used in two places and removing it makes it easier to update the configuration.
Suggested-by: \@bagedevimo
~~Review and merge after #203 because of merge conflicts.~~ *Done*
*Edit:*
The place that uses it is actually dead code. Updating it anyway, can be deleted separately (draft: #205).
=> Remove our String.shorten extension

app/controllers/users_controller.rb
The "community" nav menu only shows the "online" link to staff, however there is no corresponding authorization check to prevent non-staff from accessing that page via a direct link. This commit adds the check.
(Later on we'll add more restrictions the other "community" pages due to privacy. We are starting with the "online" page because it's not even visible in the nav menu, and because it's the only page that shows the last login time -- which is on the more sensitive side.)
See: #192
Reported-by: @thebrucecgit
=> Limit /users/online to staff

config/initializers/secret_token.rb
I should have done this from the start in #195.
(Review notes: The noise is because I renamed the variable "file" to "filename", to distinguish from the File object.)
For deploying, this will have to be applied manually (using chmod).
=> Restrict permissions on config/secret_key_base.*.txt

config/application.rb
Minimises the number of differences between the original file that Rails
generated and our configured version.
=> Move the time_zone configuration to the "default" line

config/application.rb
This value we are setting was made default in Rails 3, at least [1]. In
very modern ruby, I believe you can't even disable utf-8 parsing
anymore.
[1] https://github.com/rails/rails/commit/ec73710c79c5e1587b489b2ce05cc34138acf071
=> Remove explicit setting of config.encoding

config/application.rb
This became the default in Rails 3.1
https://github.com/rails/rails/blob/b1d57fb8c87d771d9a74ac31cd9969e6806b03b2/guides/source/3_1_release_notes.md#action-controller
=> Remove config.include_all_helpers call

app/models/problem.rb
find(:all) has been removed in Rails 4. These methods are unused, so just remove them rather than updating.
The live uses of find(:all) have already been updated in commit a26572a5 (fix deprecated scopes, finders, associations for rails 4, 2013-12-22).
=> Remove unused and broken Problem methods

config/application.rb
This silences the following Rails 4.2 deprecation warning by opting into the new behaviour:
> DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.
Docs: https://guides.rubyonrails.org/v4.2.0/upgrading_ruby_on_rails.html#error-handling-in-transaction-callbacks
The old behaviour will be removed in Rails 5 [1].
[1]\: https://github.com/rails/rails/commit/07d3d402341e81ada0214f2cb2be1da69eadfe72
---
We don't appear to use after_commit / after_rollback, so nothing to test? (The specs pass.)
=> Don't swallow errors in after_commit/after_rollback callbacks

Gemfile, Gemfile.lock
The mainstream release of qless is very unmaintained, and doesn't work with modern redis versions at all.
Shopify forked, and added a series of batches which fix a few bugs and improve a few UI quirks. Their fork is now also unmaintained, but it's more recently unmaintained, so that's nice.
=> Use the shopify fork of qless

app/controllers/file_attachments_controller.rb
`Model.scoped` was deprecated in favour of `Model.all` in Rails 4.0 [1], and removed in Rails 4.1 [2].
[1] https://github.com/rails/rails/blob/v4.0.13/activerecord/CHANGELOG.md?plain=1#L2698-L2714
[2] https://github.com/rails/rails/blob/v4.1.16/activerecord/CHANGELOG.md?plain=1#L2338
=> Fix /file_attachments page

Gemfile, Gemfile.lock
The current version has a number of deprecations, and there are no
breaking changes that should affect us until this version (1.1.0).
Going to 2.0.0 is probably possible, but not useful right now.
=> Update gem "pundit"

app/controllers/users_controller.rb
> This is an example of the N+1 query problem. Fixing it makes the pages render about twice as fast when there are many (thousands) of users.
> 
> The rest of the time is spent in the view, which is harder to optimise (there are some low-hanging fruit such as caching the policies, but they'll only get us so far; the only complete solution is to introduce paging).
> 
> See: #192
> 
> Reported-by: @thebrucecgit (and others)
For testing, the following snippet can be used to populate the database with 10,000 users:
```ruby
def create_user(id)
attrs = {username: "u#{id}", email: "u#{id}@example.com", name: "U#{id}", confirmed_at: Time.now.utc}
User.new(attrs).save!(validate: false)
end
User.transaction { (User.count + 1).upto(10000) { |i| create_user(i) } }
```
I …
=> Make /users etc. twice as fast by preloading roles

app/controllers/groups/members_controller.rb, app/controllers/groups_controller.rb, app/controllers/problem_sets_controller.rb, app/controllers/user_controller.rb, app/models/group.rb, app/views/layouts/group.html.erb, spec/features/invitation_and_join_request_spec.rb
Fixes some deprecation warnings from Rails 4.2 update (#199).
Not fully tested (only checked that the tests pass).
> Fixes the following Rails 4.2 deprecation warning:
> 
> > DEPRECATION WARNING: You are passing an instance of ActiveRecord::Base to `exists?`. Please pass the id of the object by calling `.id`.
> 
> See: https://guides.rubyonrails.org/4_2_release_notes.html#active-record-deprecations
=> Fix deprecation: pass id instead of object to `.exists?`

Gemfile, Gemfile.lock
Misc cleanup, spotted during #215 and wanted to create a PR so I won't forget. (Will probably have merge conflicts, but easy to redo.)
=> Remove unused ruby_parser gem

script/install/redis.bash
Merge after ~~#224~~. *Merged.*
We have switched (#224) to the Shopify fork of qless, which supports Redis >= 6.2.7 [1], so we can now use Redis stable again.
Reverts #156.
[1] https://www.github.com/Shopify/qless/pull/39
=> Unpin Redis version

Gemfile.lock
Extracted from #223 (because this is also important outside CI) and added links to commit message:
> This fixes the following error during `rake db:seed` on Ubuntu 20.04:
> 
> BCrypt::Errors::InvalidHash (invalid hash)
> 
> See:
> https://www.github.com/heartcombo/devise/issues/4861
> https://www.github.com/bcrypt-ruby/bcrypt-ruby/issues/165
> https://www.github.com/bcrypt-ruby/bcrypt-ruby/pull/164
=> Bump bcrypt from 3.1.11 to 3.1.20

script/install/isolate.bash
When we updated to latest version of isolate (#176), the permissions changed from 4750 to 4755 (the upstream default, allowing all users to read/execute).
On further thought, it's probably safer to prevent other users from executing isolate, just because it's setuid.
=> Prevent other users from executing 'isolate'

script/install.cfg.template, script/install/config.bash, script/install/isolate.bash, script/install/isolock.bash
Previously the scripts assumed that the group name is the same as the username, but that's not necessarily the case.
This came up in #223.
Merge using "rebase".
=> Use correct group name for isolate/isolock

.github/workflows/ci.yml, .gitignore, Gemfile, Gemfile.lock, script/install.bash, script/install/debootstrap.bash, spec/spec_helper.rb
This is a rebased and squashed version of #223 (which in turn is the successor of #82 and #150).
Closes #147.
=> Add GitHub Actions workflow for CI

config/environments/production.rb
Prior to this change, messages were being send to the ActiveSupport::Notifications system which doesn't appear to have any active listeners, meaning these notices were just being sent into the void. The notification was probably setup for a old integration (maybe newrelic?) but nothing appears to be using it at the moment.
=> Send deprecation notices to the rails log

db/schema.rb
By updating the rails version, we now get a slightly different dump format. In practise, this is the same effective result, but we should commit this new version to:
(a) ensure everyone is definitely loading the right thing when using
schema:load
(b) prevent diff's when doing a deploy which is just scary looking for
now reason.
=> Commit updated db/schema.rb

spec/controllers/file_attachments_controller_spec.rb
This broke in the rails upgrade, so following the convention of "fix a
bug, add a spec" - here's a tiny spec that was failing before the fix in
dbe5f381c577ef922ce2edd60e9dbda86ab6304b and is now passing thanks to
that commit.
=> Add a tiny spec for the file attachments page

config/environments/production.rb, config/environments/test.rb
This option is deprecated in Rails 4.2 and removed in Rails 5. There isn't a lot of rational explained in the MR, but hey.
[1] https://github.com/rails/rails/pull/18100
[2] https://github.com/rails/rails/commit/463b5d7581ee16bfaddf34ca349b7d1b5878097c
=> Update config.serve_static_assets to config.serve_static_files

.github/workflows/ci.yml
actions/checkout@v3 recently started throwing the following warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> Bump actions/checkout from 3 to 4

.github/workflows/ci.yml, script/install/config.bash, script/install/isolate.bash
This is the last version that supports cgroups v1; isolate 2.0 supports only cgroups v2.
Note that we're currently running Ubuntu 16.04. Will need to upgrade to at least 22.04 for cgroups v2 support.
=> Pin isolate to 1.10.1

script/install.bash, script/install/nokogiri.bash
As of Nokogiri 1.6, libxml2 and libxslt are bundled with Nokogiri [1], so we don't need to install the header files.
[1] https://github.com/sparklemotion/nokogiri/blob/v1.6.8.1/CHANGELOG.rdoc#label-1.6.0.rc1+-2F+2013-04-14
=> Remove nokogiri dependency packages

script/install.bash, script/install/jre.bash
Was previously openjdk-8-jdk.
- yui-compressor only requires the JRE, not the full JDK
- GUI libraries aren't required, headless version is enough
- the JRE version doesn't really matter, use the default so it gets
automatically updated
Also remove unrelated commented-out lines from JRE install script.
=> Switch to default-jre-headless on server for yui-compressor

script/install.bash, script/install/wkhtmltopdf.bash
It is used by the PDFKit gem, which is only used from app/views/item/label.html.erb. That view is not tested, so we can make
CI faster by skipping the install of wkhtmltopdf. (We can add it back if/when we write a test for the view.)
=> Skip wkhtmltopdf in CI

app/assets/stylesheets/submission.css, app/controllers/evaluators_controller.rb, app/models/evaluator.rb, app/models/submission/judge_data.rb, app/views/evaluators/_form.html.erb, app/views/evaluators/index.html.erb, app/views/evaluators/show.html.erb, app/views/problems/_admin.html.erb, app/views/submissions/show.html.erb, app/workers/judge_submission_worker.rb, db/migrate/20230225054132_add_language_id_to_evaluators.rb, db/schema.rb
This adds an optional language field to the Evaluator class. All existing/new evaluators will default to having no language, which maintains the existing functionality (script is executed as-is).
Note that C++ evaluators were already "supported" through [cint.rb](https://github.com/NZOI/nztrain/blob/8ffcd6a82ccef82d078df33863d4d6b41e1054a3/script/install/cint.rb), but that is much slower as it requires the evaluator to be recompiled on every test case. That functionality can be considered deprecated and removed later, after fixing existing evaluators.
Also note that for evaluators with no language, Pygments will attempt to automatically detect the language based on the code (see [here](https://github.com/pygments/pygments.rb/blob/7ef665b4a1247d367f5ba7a018bc0d2baf183852/lib/pygments/mentos …
=> Add support for custom evaluators using compiled langauges

app/controllers/problems_controller.rb
This pull request should resolve #257.
It displays an error message either when a submission's source has an invalid text encoding or the source contains a null character. Either conditions would have previously caused a 500 Internal Server Error.
- Having an invalid text encoding caused verification to throw an error when it tried checking if the source is blank (String#blank raises an exception when called on a string with an invalid encoding). This means that this needs to be checked before running any verification.
- If the source was valid UTF-8 but contained a null character, an error would be raised when trying to save the record because PostgreSQL does not support having null characters in strings.
=> Display an error message when submitting executable.

app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, spec/controllers/accounts/passwords_controller_spec.rb, spec/controllers/accounts/registrations_controller_spec.rb, spec/features/registrations_spec.rb
The default templates from Devise were sometimes being flagged as spam by Gmail, due to being "similar to messages that were identified as spam in the past".
Possibly fixes #270.
=> Change mailer templates to be less similar to the defaults

app/mailers/admin_mailer.rb, app/views/user/admin_email.html.erb, config/application.rb, config/environments/test.rb, config/initializers/devise.rb, config/initializers/mailer.rb, db/migrate/20120805061859_system_mailer_settings.rb, db/migrate/20250318053450_rename_setting_mailer_username_to_email.rb, db/schema.rb, db/seeds.rb, lib/development_mail_interceptor.rb
Second version of #272.
This PR renames the setting system/mailer/username to system/mailer/email and uses that for both SMTP authentication and as "from" email address (previously it was used only for SMTP authentication, and the "from" address was hard-coded to "nztrain<span>@</span>gmail.com").
It also sets the sender's display name to "NZOI Training" and cleans up a couple of things.
=> Set "from" email address using settings table instead of hard-coding

config/application.rb, spec/controllers/accounts/passwords_controller_spec.rb, spec/controllers/accounts/registrations_controller_spec.rb
This happens automatically with `config.force_ssl = true`, but [only from Rails 5](https://www.github.com/rails/rails/pull/17388).
=> Change mailer links to use https

app/controllers/filelinks/roots_controller.rb
(Minor)
Previously, /problems/:id/files/download/:path with a non-existent path would crash with Pundit::NotDefinedError (unable to find policy of nil), because `find_by_filepath` returns nil if the record is not found and then `authorize @filelink, :show?` fails.
=> Render 404 Not Found for invalid problem filelink path

README.md
This allows the README to be rendered correctly on GitHub.
[Preview](https://github.com/NZOI/nztrain/blob/44edcefb5bbdbc2ea8e3ef915fff4994d2141795/README.md)
=> Convert README to Markdown and update badges

Gemfile, Gemfile.lock
pygments.rb >= 2.0.0 runs on Python 3.x instead of Python 2.7 [1], so this allows us to run on systems without Python 2 installed.
[1] https://github.com/pygments/pygments.rb/blob/master/CHANGELOG.adoc#200rc1-2021-01-07---slonopotamus
---
@tom93 previously mentioned that pygments.rb 2.0.0 had changes related to timeout handling in #164. I haven't looked into that too much but I didn't notice any issues.
Note that this is required to update CI to run on Ubuntu 22 or 24 (which no longer comes with Python 2); see 1266f26 and 6674efa. We'll need to upgrade soon since support for Ubuntu 20 is being removed next month. Does anyone have a preference between Ubuntu 22 vs 24/latest? latest is at least ~30 slower since it doesn't come with imagemagick preinstalled.
=> Bump pygments.rb from 1.1.2 to 2.3.1

.github/workflows/ci.yml
It was previously running on ubuntu-20.04, but that is deprecated and will soon be fully unsupported [1].
[1] https://www.github.com/actions/runner-images/issues/11101
Was discussed briefly in #276.
=> Update GitHub Actions workflow to run on ubuntu-22.04

Gemfile, Gemfile.lock, app/assets/javascripts/application.js
We no longer use it directly (via 'History'), and we don't try to support ancient web browsers.
=> Remove gem "jquery-historyjs"

app/controllers/accounts/settings_controller.rb, app/controllers/contest_relations_controller.rb, app/controllers/contest_supervisors_controller.rb, app/controllers/contests_controller.rb, app/controllers/evaluators_controller.rb, app/controllers/file_attachments_controller.rb, app/controllers/groups_controller.rb, app/controllers/problem_sets_controller.rb, app/controllers/problems_controller.rb, app/controllers/roles_controller.rb, app/controllers/schools_controller.rb, app/controllers/settings_controller.rb, app/controllers/submissions_controller.rb, app/controllers/test_cases_controller.rb, app/controllers/test_sets_controller.rb, app/controllers/user_controller.rb
We don't call these methods multiple times during a single request, so there is no point in caching the result. (The example from the original strong_parameters gem doesn't use caching: https://github.com/rails/strong_parameters.)
This also eliminates silly inconsistencies with what was cached -- in some places it was @_permitted_params, while in other places it was the intermediate @_permitted_attributes.
Also remove method `visible_attributes` from user_controller.rb, it's unused since commit 8798951a (Refactor to remove the UserPresenter service object (#165), 2023-02-18).
=> Remove caching from controller permitted_params etc.

Gemfile, Gemfile.lock
Now that we've updated to Rails 4.2 we can update json to >= 2.3 and remove the CVE patch.
=> Update json gem to 2.7.6

app/controllers/contest_relations_controller.rb, config/routes.rb, spec/factories/schools.rb, spec/requests/contest_relations_request_spec.rb, spec/spec_helper.rb
Most of these actions were rendered unused in 2da020ef59c5, #destroy was
restored and #update_year_level added in 00c9636d1364. The rest of these
sections seem to be dead code, so lets remove them! Git history can
always bring them back as needed, but none of the code is particularly
interesting so it'd be easy to rewrite, anyway.
I've also specs to cover off the major functions of
contest_relations_controller, including some permission tests, and
ensured that there is at least a logged in user to slightly mitigate a
leak of information in the response differing between not_found and
unathorised on ContestRelation objects.
=> Remove unused actions on ContestRelationsController

Gemfile, Gemfile.lock
Loofah 2.21.0 added support for HTML5 (as did a later version of
Nokogiri which loofah is based off). However, we can't upgrade Nokogiri
yet due to a higher ruby version requirement. The nokogiri dependencies
aren't well constrainted for in loofah 2.21.0 so we can just stay below
that version for now, until we can upgrade ruby to 2.5, which is after
we can upgrade Rails to 5.1.
https://github.com/flavorjones/loofah/blob/main/CHANGELOG.md#2210--2023-05-10
=> Add a version constraint on loofah

db/languages.yml, db/seeds.rb, db/seeds/common.rb, db/seeds/development.rb
In order to try out different things and qa changes locally it can be
helpful to have various data in your development database. This just
makes it a little easier and safer to load that data into the dev
database repeatadly.
Also fix up how languages.yml are loaded by switching to YAML.safe_load
and dropping the symbol keys in favor of using HashWithIndifferentAccess.
=> Refactor db/seeds to allow for easy development seeds

.gitignore, spec/spec_helper.rb
This lets you use rspec features like "--only-failures" or
"--next-failure" which are very helpful when working your way through a
large change which caused a lot of test failures.
More info: https://rspec.info/features/3-12/rspec-core/command-line/only-failures/
=> Configure rspec persistence path

Gemfile, Gemfile.lock, app/controllers/contests_controller.rb, app/controllers/groups/members_controller.rb, app/controllers/home_controller.rb, app/controllers/problems_controller.rb, app/controllers/user_controller.rb, app/models/contest.rb, app/models/contest_relation.rb, app/models/contest_supervisor.rb, app/models/problem_set.rb, app/models/request.rb, app/policies/contest_policy.rb, app/policies/group_policy.rb, app/policies/problem_policy.rb, app/policies/problem_set_policy.rb, app/policies/request_policy.rb, app/policies/submission_policy.rb, app/workers/judge_submission_worker.rb, db/migrate/20131221014009_create_user_problem_relation.rb, spec/factories/contest_supervisors.rb, spec/models/contest_supervisor_spec.rb, spec/requests/submissions_request_spec.rb
This gem isn't supported on Rails >= 5, and also fully deprecated.
=> Remove the squeel gem

config/initializers/cookies_serializer.rb
Rails 4.1 introduced the new JSON format, and it becomes default in
Rails 5.0. We want to be using hybrid in production for a period of time
in order to migrate everyone to JSON before letting JSON be the default.
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#cookies-serializer
=> Configure the hybrid cookie session store

app/models/problem_set_problem.rb, spec/factories/contest_scores.rb, spec/models/problem_set_problem_spec.rb
See commit messages for more useful description of what's happened here, but it's almost entirely spec changes.
=> Fix regression in updating weighting for contest problem set problems.

config/initializers/sentry.rb
This may be too high, but our free Sentry plan includes like 1 billion
traces which is a totally bananas number. It's easy to tune, and Sentry
won't bill us if it goes over, it'll just stop accepting new traces.
=> Enable Sentry APM

script/install/bundler.bash
Gemfile.lock recently changed to say "BUNDLED WITH 1.17.3", so now Bundler 1.16 gives a warning.
=> Update Bundler install script to use Bundler 1.17

config/application.rb
This is now default in Rails 5.0, so we no longer need this opt-in
config option.
https://guides.rubyonrails.org/v6.1.0/5_0_release_notes.html#active-record-notable-changes
=> Remove config option raise_in_transaction_callbacks

app/models/language.rb, app/services/isolate.rb, app/workers/judge_submission_worker.rb, db/languages.yml, script/install/cgroup.bash, script/install/debootstrap.bash, script/install/dotnet.bash, script/install/dotnet/dotnet-csc, script/install/rbenv.bash, script/install/redis.bash, script/install/v8.bash
We're looking to switch the server to Ubuntu 24.04 (currently on Ubuntu 16.04). This shouldn't be merged until we're ready to do, but I'm opening this now if anyone wants to review.
Have tested that all current languages work. Note that any deprecated versions (e.g. Python 3.8), will not currently be available for submission/rejudging.
Note that existing custom evaluators that were previously using Ruby 2.2 (through `#!/usr/bin/env ruby`) will now use Ruby 3.2.3 instead; I tested a few and they worked fine. Evaluators that were using "Python 3.6 (PyPy 7.3.7)" as the selected language should also still work, though they'll actually be using "Python 3.11 (PyPy 7.3.19)".
Language changes:
* Python 3.8 > Python 3.13
* Python 3.6 (PyPy 7.3.7) -> Python 3.11 (PyPy 7.3.19)
* Ruby 2.2 > Ruby 3.2 …
=> Update install scripts for Ubuntu 24.04

Gemfile, Gemfile.lock, config/puma.rb
Update the puma config for actually running in production, based on the
recommended unit file from the Puma repo. Add sd_notify to the Gemfile
to so that puma can use systemd watchdog to make sure it's running
healthy and happy.
=> Productise the puma config further

config/deploy.rb
We want qless stopped before we run migrations, as a minor safety
feature and we can afford to have a minute or so of downtime of that job
system during deploys in return for not having to be quite so agressive
about migration safety that could affect running jobs.
We boot it back up again at the end.
=> Correctly manage qless during the deploy lifecycle

config/deploy.rb
By specifying DEPLOY_BRANCH=<branch_name> a different branch will be
deployed to the specified environment, instead of the default master.
=> Allow overriding the deploy branch during a cap deploy
